[pytket-honeywell] Add option to store credentials in memory.
CQCL/pytket-extensions pull request #251
Opened 2021-12-10 12:37 UTC by vanyae-cqc

This PR enables the `HoneywellQAPI` api wrapper to optionally store credentials (password, id_token and refresh_token) in memory as opposed to in persistent storage via `keyring`. Persistent storage is used by default.

I've done reasonably thorough manual testing, but haven't added any `pytest` tests as testing credential-related features doesn't appear to be standard across the pytket-extensions. Very happy to make any desired changes.

2021-12-10 16:44 UTC, ss2165 requested changes
I think tests are appropriate here, the two credential services can be tested for save/retrieve with some dummy credentials

The api handler would require some mocking to test against I guess?

2021-12-13 14:39 UTC, vanyae-cqc commented
Cool, I've updated with new tests for the `CredentialStorage` and one of the `HoneywellQAPI` methods that isn't covered in the existing test files.

2021-12-13 14:47 UTC, vanyae-cqc commented on modules/pytket-honeywell/tests/conftest.py
> +    """A logged-in HoneywellQAPI fixture."""
Yes I believe it could, I originally opted away from it because it'll cause duplication elsewhere but I'll take another look.

2021-12-13 16:01 UTC, vanyae-cqc commented on modules/pytket-honeywell/tests/conftest.py
> +    """A logged-in HoneywellQAPI fixture."""
Cool, I've refactored it a little and it looks better. Thanks for the good suggestion.

2021-12-13 17:42 UTC, ss2165 submitted a review, later dismissed

2021-12-14 15:09 UTC, ss2165 approved these changes

2021-12-14 15:09 UTC, merged