add pyzx arc conversion
CQCL/pytket-extensions pull request #393
Opened 2022-05-17 14:08 UTC by cqc-melf

2022-05-20 10:02 UTC, cqc-alec requested changes

2022-05-20 10:02 UTC, cqc-alec commented on modules/pytket-pyzx/tests/pyzx_convert_test.py
> +    assert pytket_circ_2.qubits == c.qubits
Can we check for circuit equality?

2022-05-20 13:54 UTC, cqc-melf commented on modules/pytket-pyzx/pytket/extensions/pyzx/pyzx_convert.py
> +        arc_dict[x] = qubit_dict[q_map[x]]
That is only possible if the qubits are sorted, or do you mean something else?

2022-05-20 13:55 UTC, cqc-melf commented on modules/pytket-pyzx/pytket/extensions/pyzx/__init__.py
> +    pyzx_to_pytket_placed_circ,
done in @cqc-melf
[rename pytket to tk in functionnames](https://github.com/CQCL/pytket-extensions/pull/393/commits/bcb333904b31ca9cb13a782ced7afc33d77f6eb1)
[bcb3339](https://github.com/CQCL/pytket-extensions/pull/393/commits/bcb333904b31ca9cb13a782ced7afc33d77f6eb1)

2022-05-20 13:55 UTC, cqc-melf commented on modules/pytket-pyzx/pytket/extensions/pyzx/pyzx_convert.py
> +from pyzx.routing.architecture import Architecture as pyzxarc  # type: ignore
done in @cqc-melf
[rename pyzxarc to PyzxArc](https://github.com/CQCL/pytket-extensions/pull/393/commits/edb7cd3aaa426f3a8b55487d2e7eb9a169164e9d)
[edb7cd3](https://github.com/CQCL/pytket-extensions/pull/393/commits/edb7cd3aaa426f3a8b55487d2e7eb9a169164e9d)

2022-05-20 13:55 UTC, cqc-melf commented on modules/pytket-pyzx/pytket/extensions/pyzx/pyzx_convert.py
> +    in the node set of the pytket.
done in @cqc-melf
[rename pyzxgraph to PyzxGraph](https://github.com/CQCL/pytket-extensions/pull/393/commits/84c833c261aa04b9d44cbcefca8ba809416c9947)
[84c833c](https://github.com/CQCL/pytket-extensions/pull/393/commits/84c833c261aa04b9d44cbcefca8ba809416c9947)

2022-05-20 13:57 UTC, cqc-melf commented on modules/pytket-pyzx/pytket/extensions/pyzx/pyzx_convert.py
> +from pyzx.graph.graph import Graph as pyzxgraph  # type: ignore
done in @cqc-melf
[rename pyzxgraph to PyzxGraph](https://github.com/CQCL/pytket-extensions/pull/393/commits/84c833c261aa04b9d44cbcefca8ba809416c9947)
[84c833c](https://github.com/CQCL/pytket-extensions/pull/393/commits/84c833c261aa04b9d44cbcefca8ba809416c9947)

2022-05-20 13:57 UTC, cqc-melf commented on modules/pytket-pyzx/pytket/extensions/pyzx/pyzx_convert.py
> +    in the node set of the pytket.
done in @cqc-melf
[replace in the node set of .](https://github.com/CQCL/pytket-extensions/pull/393/commits/73d062ab69df90daf79e4d12752169ccfa427755)
[73d062a](https://github.com/CQCL/pytket-extensions/pull/393/commits/73d062ab69df90daf79e4d12752169ccfa427755)

2022-05-20 13:58 UTC, cqc-melf commented on modules/pytket-pyzx/pytket/extensions/pyzx/pyzx_convert.py
> +    pyzx_arc = pyzxarc("pyzx_arc", coupling_graph=arcgraph)
have added that for both functions

done in @cqc-melf
[add parameter for src name in pyzx](https://github.com/CQCL/pytket-extensions/pull/393/commits/d12d8b65a6608eac4b021e4bf631846b1adcd361)
[d12d8b6](https://github.com/CQCL/pytket-extensions/pull/393/commits/d12d8b65a6608eac4b021e4bf631846b1adcd361)

2022-05-20 13:58 UTC, cqc-melf commented on modules/pytket-pyzx/pytket/extensions/pyzx/pyzx_convert.py
> +    return pytket_arc
done in @cqc-melf
[return directly in pyzx_to_tk_arc](https://github.com/CQCL/pytket-extensions/pull/393/commits/6a353c50d65090e2d2d41b054185a7030065bcba)
[6a353c5](https://github.com/CQCL/pytket-extensions/pull/393/commits/6a353c50d65090e2d2d41b054185a7030065bcba)

2022-05-20 13:59 UTC, cqc-melf commented on modules/pytket-pyzx/pytket/extensions/pyzx/pyzx_convert.py
> +    pyzx_arc = pyzxarc("pyzx_arc", coupling_graph=arcgraph)
done in @cqc-melf
[add parameter for src name in pyzx](https://github.com/CQCL/pytket-extensions/pull/393/commits/d12d8b65a6608eac4b021e4bf631846b1adcd361)
[d12d8b6](https://github.com/CQCL/pytket-extensions/pull/393/commits/d12d8b65a6608eac4b021e4bf631846b1adcd361)

2022-05-20 14:00 UTC, cqc-melf commented on modules/pytket-pyzx/pytket/extensions/pyzx/pyzx_convert.py
> +    `pyzx_circuit_name.to_basic_gates()` before conversion.
Removed that for the old function documentation as well, see @cqc-melf
[remove >>all PyZX basic gate operations are currently supported by py…](https://github.com/CQCL/pytket-extensions/pull/393/commits/500807d7467a485567ff783e32484ed934a998ba)
[500807d](https://github.com/CQCL/pytket-extensions/pull/393/commits/500807d7467a485567ff783e32484ed934a998ba)

2022-05-20 14:00 UTC, cqc-melf commented on modules/pytket-pyzx/pytket/extensions/pyzx/pyzx_convert.py
> +        map for conversion
done in @cqc-melf
[add more information about the map in the documentation](https://github.com/CQCL/pytket-extensions/pull/393/commits/d2a1a0a2bd894aa6858f5df441c6f29fb5de5330)
[d2a1a0a](https://github.com/CQCL/pytket-extensions/pull/393/commits/d2a1a0a2bd894aa6858f5df441c6f29fb5de5330)

2022-05-20 14:01 UTC, cqc-melf commented on modules/pytket-pyzx/pytket/extensions/pyzx/pyzx_convert.py
> +    :param q_map: placment map
done in @cqc-melf
[add more information to the doc about the map parameter](https://github.com/CQCL/pytket-extensions/pull/393/commits/7b3dc2de28f40b48cf9b6a757552fc2f255a7513)
[7b3dc2d](https://github.com/CQCL/pytket-extensions/pull/393/commits/7b3dc2de28f40b48cf9b6a757552fc2f255a7513)

2022-05-20 14:01 UTC, cqc-melf commented on modules/pytket-pyzx/tests/pyzx_convert_test.py
> +    assert pytket_circ_2.qubits == c.qubits
I have added a state comparison, is that what you had in mind? done in @cqc-melf
[add check for circuit equality](https://github.com/CQCL/pytket-extensions/pull/393/commits/f34943fb98fed2898b7e6a5d1e07074e75a50277)
[f34943f](https://github.com/CQCL/pytket-extensions/pull/393/commits/f34943fb98fed2898b7e6a5d1e07074e75a50277)

2022-05-20 14:01 UTC, cqc-melf commented on modules/pytket-pyzx/tests/pyzx_convert_test.py
> +    assert pytket_circ_2.qubits == c.qubits
see above

2022-05-25 07:46 UTC, cqc-alec commented on modules/pytket-pyzx/pytket/extensions/pyzx/pyzx_convert.py
> +        arc_dict[x] = qubit_dict[q_map[x]]
No, ignore me.

2022-05-25 07:47 UTC, cqc-alec approved these changes

2022-06-06 08:03 UTC, merged