added defcomp info for QuantinuumBackend
CQCL/pytket-extensions pull request #408
Opened 2022-05-31 13:31 UTC by CalMacCQ

Added docs page for default compilation for the Quantinuum Backend. Once I have the right content it should be quick to do for the other backends.

2022-06-01 10:10 UTC, ss2165 commented on modules/pytket-quantinuum/docs/intro.txt
> +   * - DecomposeClassicalExp
note this will need changing after #385

2022-06-01 10:10 UTC, ss2165 commented on modules/pytket-quantinuum/docs/intro.txt
> +     - self.rebase_pass
add a footnote explaining what this is

2022-06-01 10:12 UTC, ss2165 commented on modules/pytket-quantinuum/docs/intro.txt
> +            ``get_compiled_circuit`` method. More intensive optimisation is applied by level 2 at the expense of increased runtime.
you're talking about the `get_compiled_circuit` method, so "equivalent" doesn't make sense here?

2022-06-01 10:12 UTC, ss2165 commented on modules/pytket-quantinuum/docs/intro.txt
> +* [2] ``auto_squash_pass`` has arguments ``auto_squash_pass(OpType.PhasedX,OpType.Rz)``
```suggestion
* [2] ``auto_squash_pass`` has arguments ``auto_squash_pass({OpType.PhasedX,OpType.Rz})``
```

2022-06-15 16:36 UTC, ss2165 requested changes
Almost there! Just a couple of requests:

* login, logout,  device_state, cancel missing from the additional functionality section
* the status, result handle type and result type sections could do with their own headings

2022-06-22 10:36 UTC, cqc-alec requested changes

2022-06-22 10:36 UTC, cqc-alec commented on modules/pytket-quantinuum/docs/intro.txt
> +* ``H1-1E``, ``H1-2E``: Device-specific Emulators of ``H1-1`` and ``H1-2``. These emulators run remotely on servers and require credentials.
```suggestion
* ``H1-1E``, ``H1-2E``: Device-specific emulators of ``H1-1`` and ``H1-2``. These emulators run remotely on servers and require credentials.
```

2022-06-22 10:36 UTC, cqc-alec commented on modules/pytket-quantinuum/docs/intro.txt
> +* ``H1``: Submit to Quantinuum System Model ``H1`` machines, job is run on ``H1-1`` or ``H1-2`` based on soonest available device.
```suggestion
* ``H1``: Submit to Quantinuum System Model ``H1`` machines: job is run on ``H1-1`` or ``H1-2`` based on soonest available device.
```
Is "Quantinuum System Model" a proper name?

2022-06-22 10:36 UTC, cqc-alec commented on modules/pytket-quantinuum/docs/intro.txt
> +The H-series devices and emulators produce shots based results and therefore require measurements. The emulators use noise models based on the real devices.
```suggestion
The H-series devices and emulators produce shots-based results and therefore require measurements. The emulators use noise models based on the real devices. 
```

2022-06-22 10:36 UTC, cqc-alec commented on modules/pytket-quantinuum/docs/intro.txt
> +* completed - the job has finished.
```suggestion
* completed - The job has finished.
```

2022-06-22 10:36 UTC, cqc-alec commented on modules/pytket-quantinuum/docs/intro.txt
> +* failed - job has failed.
```suggestion
* failed - The job has failed.
```

2022-06-22 10:36 UTC, cqc-alec commented on modules/pytket-quantinuum/docs/intro.txt
> +* cancelling - the job is in the process of being cancelled.
```suggestion
* cancelling - The job is in the process of being cancelled.
```

2022-06-22 10:36 UTC, cqc-alec commented on modules/pytket-quantinuum/docs/intro.txt
> +* cancelled - the job has been cancelled.
```suggestion
* cancelled - The job has been cancelled.
```

2022-06-22 10:36 UTC, cqc-alec commented on modules/pytket-quantinuum/docs/intro.txt
> +.. list-table:: **Default compilation pass for the Quantinuum Backend**
```suggestion
.. list-table:: **Default compilation pass for the Quantinuum backends**
```

2022-06-22 10:36 UTC, cqc-alec commented on modules/pytket-quantinuum/docs/intro.txt
> +* [2] ``self.rebase_pass`` is a rebase that converts the circuit to the Quantinuum native gate set {Rz, PhasedX, ZZMax, ZZPhase}.
```suggestion
* [2] ``self.rebase_pass`` is a rebase that converts the circuit to the Quantinuum native gate set (e.g. {Rz, PhasedX, ZZMax, ZZPhase}).
```

2022-06-22 10:36 UTC, cqc-alec commented on modules/pytket-quantinuum/docs/intro.txt
> +* [4] ``SimplifyInitial`` has arguments  ``SimplifyInitial(allow_classical=False, create_all_qubits=True, xcirc=xcirc)``
This is incomplete without code context (what is `xcirc`?). Do we wantthis level of detail here?

2022-06-22 10:36 UTC, cqc-alec commented on modules/pytket-quantinuum/docs/intro.txt
> +* `NoSymbolsPredicate  <https://cqcl.github.io/tket/pytket/api/predicates.html#pytket.predicates.NoSymbolsPredicate>`_  - Parameterised gates must have numerical parameters when the circuit is execut
```suggestion
* `NoSymbolsPredicate  <https://cqcl.github.io/tket/pytket/api/predicates.html#pytket.predicates.NoSymbolsPredicate>`_  : Parameterised gates must have numerical parameters when the circuit is executed.
```

2022-06-22 10:36 UTC, cqc-alec commented on modules/pytket-quantinuum/docs/intro.txt
> +* `GateSetPredicate  <https://cqcl.github.io/tket/pytket/api/predicates.html#pytket.predicates.GateSetPredicate>`_ : To view supported Ops run ``QuantinuumBackend.backend_info.gate_set``
```suggestion
* `GateSetPredicate  <https://cqcl.github.io/tket/pytket/api/predicates.html#pytket.predicates.GateSetPredicate>`_ : To view supported Ops run ``QuantinuumBackend.backend_info.gate_set``.
```

2022-06-22 10:36 UTC, cqc-alec commented on modules/pytket-quantinuum/docs/intro.txt
> +The Quantinuum ``Backend`` has a ``cost`` method. This calculates the cost (in H-series Quantum Credits) required to execute the circuit for the specified number of shots.
```suggestion
The Quantinuum ``Backend`` has a ``cost`` method. This calculates the cost (in HQS) required to execute the circuit for the specified number of shots.  
```

2022-06-22 10:36 UTC, cqc-alec commented on modules/pytket-quantinuum/docs/intro.txt
> +*  ``close_batch`` : boolean flag to close the batch after the last circuit in the job, ``default=True``.
```suggestion
*  ``close_batch`` : boolean flag to close the batch after the last circuit in the job (default value is ``True``).
```

2022-06-22 10:36 UTC, cqc-alec commented on modules/pytket-quantinuum/docs/intro.txt
> +For the Quantinuum ``Backend``, ``process_circuits`` returns a ResultHandle object containing a ``job_id`` and a postprocessing ( ``ppcirc``) circuit if there is one. The ``logout()`` method clears s
```suggestion
For the Quantinuum ``Backend``, ``process_circuits`` returns a ``ResultHandle`` object containing a ``job_id`` and a postprocessing ( ``ppcirc``) circuit if there is one. The ``logout()`` method clears stored JSON web tokens and will have to sign in to access the Quantinuum API.
```

2022-06-22 10:36 UTC, cqc-alec commented on modules/pytket-quantinuum/docs/intro.txt
> +For the Quantinuum ``Backend``, ``process_circuits`` returns a ResultHandle object containing a ``job_id`` and a postprocessing ( ``ppcirc``) circuit if there is one. The ``logout()`` method clears s
Are there some words missing before "will have to sign in", e.g. "after calling this method the user" ...?

2022-06-22 10:36 UTC, cqc-alec commented on modules/pytket-quantinuum/docs/intro.txt
> +Every Quantinuum ``Backend`` supports mid circuit measurements.
```suggestion
Every Quantinuum ``Backend`` supports mid-circuit measurements.
```

2022-06-27 13:42 UTC, CalMacCQ commented on modules/pytket-quantinuum/docs/intro.txt
> +    changelog.rst
I'm not sure what happened here was the `changelog.rst` line not showing?

2022-06-27 16:01 UTC, ss2165 requested changes

2022-06-28 09:07 UTC, CalMacCQ commented on modules/pytket-quantinuum/docs/intro.txt
> +The pytket-quantinuum extension allows the user to access the following quantum devices, emulators and syntax checkers. These backends can be initialised  by passing the device name as a string to th
Is what I've added on this adequate now?

2022-06-28 09:13 UTC, ss2165 submitted a review, later dismissed

2022-07-01 13:32 UTC, cqc-alec approved these changes

2022-07-01 13:49 UTC, merged