add def comp info for pytket-qiskit
CQCL/pytket-extensions pull request #466
Opened 2022-08-03 11:15 UTC by CalMacCQ

I've added a list of backends to the docs page for pytket qiskit. I've also added info on the default_compilation_pass for different levels of optimisation. 

Let me know if I've missed anything and if more detail is needed.

2022-08-04 09:47 UTC, ss2165 requested changes
Things I spotted on the quantinuum intro worth including here https://github.com/CQCL/pytket-quantinuum/blob/develop/docs/intro.txt:

* predicates
* statuses
* backend init parameters, most importantly how to authenticate with a particular hub/group/use a specific authentication provider.
* how batching works
* kwargs to process_circuits and get results
* what the result handle means
*

2022-08-04 09:47 UTC, ss2165 commented on modules/pytket-qiskit/docs/intro.txt
> +* [3] self.rebase_pass is a rebase to the IBM native gate set (e.g. {X, SX, Rz, CX}).
"gate set supported by the backend, for IBM quantum devices that is {X, SX, Rz, CX}"

2022-08-04 09:47 UTC, ss2165 commented on modules/pytket-qiskit/docs/intro.txt
> +* [1] By default ``AerBackend`` is noiseless by default and has no architecture. However it can accept a user defined ``NoiseModel`` and ``Architecture``.
Worth adding more detail on how to do noisy simulation

2022-10-11 14:34 UTC, cqc-melf commented
Is this something you want to get moved over to the new repo? https://github.com/CQCL/pytket-qiskit/

2022-10-11 14:37 UTC, CalMacCQ commented
Yes, if thats possible to do. 

This was something I meant to finish ages ago but moved onto other things. I think it would be worth finishing this soon.

I also have a copy of everything locally

2022-10-11 14:38 UTC, cqc-melf commented
Okay, will do that.

2022-10-11 14:55 UTC, cqc-melf commented
reopened at https://github.com/CQCL/pytket-qiskit/pull/3

2022-10-11 14:55 UTC, closed without merging