Support ECRGate in `pytket-qiskit` circuit conversion
CQCL/pytket-extensions pull request #479
Opened 2022-09-06 12:53 UTC by burgholzer

At the moment, attempting to convert a tket circuit containing `ecr` gates (one of the basis gates in OQC's quantum computers) to a qiskit circuit (via the `tk_to_qiskit` method) raises the following error
```console
NotImplementedError: Cannot convert tket Op to Qiskit gate: ECR
```
This simple PR fixes the underlying issue by adding the `ECRGate` to the `_qiskit_gates_2q` list in the qiskit converter.
As a result, circuits compiled to the OQC device using tket can be translated to Qiskit without errors.

2022-09-07 08:14 UTC, ss2165 requested changes
Unfortunately, the OQC ECR gate and the Qiskit OCR gate are not exactly the same. [Qiskit defines it as RZX(pi/2)](https://qiskit.org/documentation/stubs/qiskit.circuit.library.ECRGate.html), but the ECR OpType in pytket, which maps to OQC, is RZX(-pi/2)

![image](https://user-images.githubusercontent.com/12997250/188811780-c298d645-93e4-4603-b452-a30c2feedac3.png)
![image](https://user-images.githubusercontent.com/12997250/188811809-d3208c6d-417b-4703-944d-e82d02abb7ac.png)

https://cqcl.github.io/tket/pytket/api/optype.html

The two gates are not equivalent up to global phase, and extra single qubit gates are needed to map them. (I believe a Z gate on one qubit and an X on the other). You could potentially add some special case handling for this, and use a unitary simulator to verify the conversion.

2022-09-07 10:19 UTC, burgholzer commented
Thanks for pointing that out!

Please correct me if I am wrong, but I believe the difference is much simpler than that. The answer actually is in the link to the Qiskit definition you provided above (https://qiskit.org/documentation/stubs/qiskit.circuit.library.ECRGate.html).
Namely, Qiskit's little endian qubit ordering convention makes the difference, i.e., 
```
ECR_QISKIT(q[0], q[1]) = ECR_TKET(q[1], q[0])
```
If that is correct, special casing should be much easier. I'll happily work on this, but would first wait for your confirmation.

2022-09-07 10:39 UTC, ss2165 commented
Yes you're right, my answer is outdated and we have since updated ECR to be compatible. My colleague @yao-cqc will confirm this and reply.

2022-09-07 11:00 UTC, yao-cqc commented
@burgholzer You are correct, the two ECR gates have the same definition. Endianness only affect how we present the matrices. I believe no special case handling is required.

2022-09-07 11:11 UTC, burgholzer commented
thanks for the clarification! Then this PR should be complete as it is, right?

2022-09-07 11:19 UTC, yao-cqc commented
> thanks for the clarification! Then this PR should be complete as it is, right?

Yes, I think it's good. It would be great if you can also add an entry to `modules/pytket-qiskit/docs/changelog.rst`.

2022-09-07 11:44 UTC, yao-cqc approved these changes
All looks good to me. Thanks!

2022-09-08 07:10 UTC, ss2165 approved these changes

2022-09-08 07:10 UTC, merged

2022-09-08 07:11 UTC, ss2165 commented
Thanks @burgholzer!